import type { Worker, FunctionDefinition } from '../shared/contracts.js';
export const WORKERS: Worker[] = [
  {
    id: 'researcher',
    name: 'Scout',
    role: 'Research',
    position: 'Market research analyst',
    department: 'Strategy',
    manager_id: 'operator',
    kind: 'agent',
    purpose: 'Develop a research brief for real team tasks and select virtual-sale hypotheses.',
    permissions: [
      'Read product concepts',
      'Develop supplied-information briefs',
      'Select scenario product',
    ],
    restrictions: ['No external research or outreach', 'Cannot spend or post revenue'],
  },
  {
    id: 'creator',
    name: 'Studio',
    role: 'Product creation',
    position: 'Digital product designer',
    department: 'Production',
    manager_id: 'operator',
    kind: 'agent',
    purpose: 'Create text deliverables for real team tasks and virtual-sale specifications.',
    permissions: [
      'Generate text through subscription-authenticated Codex',
      'Prepare delivery specification',
    ],
    restrictions: ['No external publication or payments', 'Cannot certify its own quality'],
  },
  {
    id: 'reviewer',
    name: 'Review',
    role: 'Quality',
    position: 'Quality assurance reviewer',
    department: 'Production',
    manager_id: 'operator',
    kind: 'agent',
    purpose: 'Independently review generated team work and validate virtual-sale metadata.',
    permissions: [
      'Review generated text',
      'Validate delivery specification',
      'Block invalid specifications',
    ],
    restrictions: ['Cannot alter spending policy', 'Cannot certify real products'],
  },
  {
    id: 'operator',
    name: 'Operator',
    role: 'Business operations',
    position: 'Digital business manager',
    department: 'Operations',
    manager_id: 'owner',
    kind: 'agent',
    purpose: 'Delegate owner goals, deliver reviewed team work, and coordinate virtual sales.',
    permissions: [
      'Delegate and synthesize generated text',
      'Run permitted scenario workflows',
      'Request ledger posting through Treasury',
    ],
    restrictions: ['No live accounts or payments', 'Cannot bypass treasury checks'],
  },
  {
    id: 'treasury',
    name: 'Treasury',
    role: 'Financial control',
    position: 'Deterministic finance and policy service',
    department: 'Controls',
    manager_id: 'owner',
    kind: 'control',
    purpose: 'Enforce financial limits and post balanced journal entries.',
    permissions: [
      'Authorize bounded virtual costs',
      'Post balanced entries',
      'Block unsafe commitments',
    ],
    restrictions: ['No LLM authority', 'Protected reserve cannot be disabled'],
  },
];
export const FUNCTIONS: FunctionDefinition[] = [
  {
    id: 'select_product',
    title: 'Select product hypothesis',
    worker_id: 'researcher',
    engine: 'scripted',
    inputs: ['Product identifier', 'Product catalog'],
    outputs: ['Scenario product metadata'],
    depends_on: [],
    source: 'src/server/service.ts \u00b7 cycle',
  },
  {
    id: 'authorize_budget',
    title: 'Authorize production budget',
    worker_id: 'treasury',
    engine: 'control',
    inputs: ['Maximum scenario cost', 'Cash, holds and limits'],
    outputs: ['Permission or policy denial'],
    depends_on: ['select_product'],
    source: 'src/server/treasury.ts \u00b7 authorize',
  },
  {
    id: 'prepare_delivery',
    title: 'Prepare delivery specification',
    worker_id: 'creator',
    engine: 'scripted',
    inputs: ['Scenario product metadata'],
    outputs: ['Price, cost and simulation-only specification'],
    depends_on: ['authorize_budget'],
    source: 'src/server/workflows.ts \u00b7 prepareDelivery',
  },
  {
    id: 'check_delivery',
    title: 'Validate delivery specification',
    worker_id: 'reviewer',
    engine: 'control',
    inputs: ['Delivery specification'],
    outputs: ['Validated specification or rejection'],
    depends_on: ['prepare_delivery'],
    source: 'src/server/workflows.ts \u00b7 checkDelivery',
  },
  {
    id: 'settle_order',
    title: 'Deliver and settle virtual order',
    worker_id: 'operator',
    engine: 'scripted',
    inputs: ['Validated specification'],
    outputs: ['Virtual order and settlement reference'],
    depends_on: ['check_delivery'],
    source: 'src/server/service.ts \u00b7 cycle',
  },
  {
    id: 'post_ledger',
    title: 'Post balanced financial entries',
    worker_id: 'treasury',
    engine: 'control',
    inputs: ['Virtual settlement and scenario costs'],
    outputs: ['Sale and expense journal entries'],
    depends_on: ['settle_order'],
    source: 'src/server/treasury.ts \u00b7 post',
  },
];
export const WORKER_BY_ID = new Map(WORKERS.map((w) => [w.id, w]));
export const FUNCTION_BY_ID = new Map(FUNCTIONS.map((f) => [f.id, f]));
export const AGENT_ROLES = WORKERS.filter((w) => w.kind === 'agent');
